name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.5.3
    - name: set up JDK 20
      uses: actions/setup-java@v3.11.0
      with:
        java-version: '20'
        distribution: 'oracle'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleDebug
    - name: Change APK name
      run: mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/basic-matics.apk
    - name: Upload Build APK
      uses: actions/upload-artifact@v3.1.2
      with:
        name: Build APK
        path: app/build/outputs/apk/debug/basic-matics.apk
